---
wiki_approval_settings_comment: 'false'
wiki_approval_settings_draft_enabled: 'true'
wiki_approval_settings_enabled: 'project'
wiki_approval_settings_required: 'project'
wiki_approval_settings_version: 'true'
wiki_approval_settings_content_draft: 'true'
wiki_approval_settings_sidebar_project: 0
wiki_approval_settings_sidebar_status:
  - canceled
  - draft
  - pending
  - rejected
  - released
  - published